### ISSUE TITLE
misconfiguration of website

### ISSUE THREAD

**Issue by robertoostenveld** [wiringX/wiringx-manual#4]
The page https://manual.pilight.org/configuration/hardware.html refers to http://www.wiringx.org, which returns a 404 "Site not found" error. 

When I go to http://wiringx.org without the www, and click through some certificate issue, the site does show up.

**Comment by CurlyMoo** [comment]
Thanks for reporting. I will look into it.

**Comment by robertoostenveld** [comment]
I now notice that the README at https://github.com/wiringX/wiringX points to https://manual.wiringx.org. That one works fine.

**Comment by CurlyMoo** [comment]
I think i should just redirect to https://manual.wiringx.org by default.

**Comment by CurlyMoo** [comment]
It should be fixed.

**Comment by robertoostenveld** [comment]
confirmed, thanks!
